name: EveryFive

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    name: Get Data
    if: "!contains(toJSON(github.event.commits.*.message), '[skip-ci]')"
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: NPM ops
      shell: bash
      run: |
        yarn
        yarn start
      env:
        # CI: true
        # IFTTT_WEBHOOKS_KEY: ${{ secrets.IFTTT_WEBHOOKS_KEY }}
        # IFTTT_EVENT: ${{ secrets.IFTTT_EVENT }}
        # OS_REST_KEY: ${{ secrets.OS_REST_KEY }}
        # OS_APP_ID: ${{ secrets.OS_APP_ID }}
        # CITIES_DELIMITED_WITH_SEMICOLON: ${{ secrets.CITIES_DELIMITED_WITH_SEMICOLON }}
        # MIN_MAGNITUDE: ${{ secrets.MIN_MAGNITUDE }}
    - name: Upload files
      uses: actions/upload-artifact@v2
      with:
        name: tweet
        path: tweet.txt
    - run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
        git diff-index --quiet HEAD || git commit -m "Add [skip-ci]"
        git push
